# actions
# common settings for all actions in this controller
common:
  metas:
    name:
      keywords: One, Night, Only, Armani, Giorgio, Prive, Fashion, Show, NYC
      description:
      robots: index, follow
    property:
      og:image: assets/img/og/social.jpg
      
# configs for each action
index:
  title: Giorgio Armani | One night only Social Wall
  
  