# actions
# common settings for all actions in this controller
common:
  metas:
    name:
      keywords: One, Night, Only, Armani, Giorgio, Emporio, Fashion, Show, Rome, Roma
      description:
      robots: index, follow
    property:
      og:image: assets/img/og/ono-roma.jpg
      
# configs for each action
index:
  title: Giorgio Armani | One night only Social Stream
  
  
  og:
    index og:image: assets/img/og/socia.jpg