has_layout: true

layout:
  default

default:
  title: Giorgio Armani | One Night Only in Roma

  metas:
    https:
      content-type: text/html; charset=utf-8
      content-language: en-US

    name:
      keywords: Giorgio, Armani, One Night Only, Fashion, Festa, Show, Rome, Live, Event
      description: The source for the biggest event of the year. See all of the One night only content here.
      robots: index, follow

  css:
    site:
      - bootstrap-social
      - bootstrap.min
      - bootstrap-responsive.min
      - main
      - royalslider/royalslider

  js:
    cdn:


    site:
      - vendor/jquery-1.9.1.min
      - vendor/jquery-ui-1.10.3.custom
      - vendor/imagesloaded
      - vendor/bootstrap.min
      - vendor/jquery.countdown.min      
      - vendor/jquery.imgpreload.min
      - vendor/jquery.zoomooz
      - vendor/jquery.bgswitcher
      - vendor/jquery.transit.min
      - vendor/jquery.pjax
      - vendor/jquery.fittext
      - vendor/spin.min
      - vendor/jquery.spin      
      - vendor/jquery.cookie
      - vendor/jquery.scrollTo.min
      - vendor/waypoints
      - vendor/waypoints-infinite
      - royalslider/jquery.royalslider.min
      - main