has_layout: true

layout:
  default

default:
  title: Giorgio Armani | One Night Only in Roma

  metas:
    https:
      content-type: text/html; charset=utf-8
      content-language: en-US

    name:
      keywords: Giorgio, Armani, One Night Only, Fashion, Festa, Show, Rome, Live, Event
      description: The source for the biggest event of the year. See all of the One night only content here.
      robots: index, follow
      viewport: width=device-width, initial-scale=1.0, minimum-scale=0.5, maximum-scale=1.0, user-scalable=no

  css:
    site:
      - bootstrap-social
      - bootstrap.min
      - bootstrap-responsive.min
      - main
      - royalslider/royalslider

  js:
    cdn:


    site:
      - vendor/jquery-1.9.1.min
      - vendor/bootstrap.min
      - vendor/jquery.countdown.min
      - vendor/jquery.imgpreload.min
      - vendor/jquery.zoomooz
      - vendor/jquery.bgswitcher
      - vendor/jquery.transit.min
      - vendor/jquery.pjax
      - vendor/jquery.fittext
      - vendor/jquery.scrollTo.min
      - main
      - royalslider/jquery.royalslider.min
      
