# actions
# common settings for all actions in this controller
common:
  title: One Night Only
  css:
    site:
      
  js:
    site:
      
# configs for each action
index:
  title: Giorgio Armani | One night only

  metas:
    name:

  css:
    site:

   