# actions
# common settings for all actions in this controller
common:
  title: One Night Only
  css:
    site:
      
  js:
    site:
      
# configs for each action
index:
  title: Giorgio Armani | One night only

  metas:
    name:
      keywords: One, Night, Only, Armani, Giorgio, Emporio, Fashion, Show, Rome, Roma
      description: Giorgio Armani One night only Roma. The event of the year.
      robots: index, follow
    property:
      og:image: assets/img/og/may-30.jpg

countdown:
  title: Giorgio Armani | One night only - Countdown
  
  test:
    firstlevel: yeah man
  
  metas:
     name:
       keywords: test, tester
       
may-30:
   title: Giorgio Armani | One night only - May 30th

   metas:
     name:
       keywords: One, Night, Only, Armani, Giorgio, Emporio, Fashion, Show, Rome, Roma
       description: Giorgio Armani One night only Roma. The event of the year.
       robots: index, follow
     property:
       og:image: assets/img/og/may-30.jpg