# actions
# common settings for all actions in this controller
common:
  title: One Night Only
  css:
    site:
      
  js:
    site:
      
# configs for each action
index:
  title: Giorgio Armani | One night only roma

  metas:
    name:
      keywords: One, Night, Only, Armani, Giorgio, Emporio, Fashion, Show, Rome, Roma
      description: Giorgio Armani One night only Roma. The event of the year.
      robots: index, follow
    property:
      og:image: assets/img/og/ono-roma.jpg

countdown:
  title: Giorgio Armani | One night only - Counting down
  
  og:
    may-30 og:image: assets/img/og/ono-roma.jpg
    may-31 og:image: assets/img/og/may-31.jpg
    june-1 og:image: assets/img/og/june-1.jpg
    june-2 og:image: assets/img/og/june-2.jpg
    june-3 og:image: assets/img/og/june-3.jpg
    june-4 og:image: assets/img/og/june-4.jpg
    june-5 og:image: assets/img/og/ono-roma.jpg
    june-6 og:image: assets/img/og/june-6.jpg
    june-7 og:image: assets/img/og/june-7.jpg
    june-8 og:image: assets/img/catwalk/GA/one_night_only-GA_2.jpg
    june-9 og:image: assets/img/milla-jovovich_interview.jp
    june-10 og:image: assets/img/muti_interview.jpg
    june-11 og:image: assets/img/og/june-11.jpg
    june-12 og:image: assets/img/og/june-12.jpg
    june-13 og:image: assets/img/og/june-13.jpg