# actions
# common settings for all actions in this controller
common:
      
# configs for each action
index:
  title: Giorgio Armani | Events

  metas:
    name:
      
rome:
  title: Giorgio Armani | One night only Roma

  metas:
    name:
      
beijing:
  title: Giorgio Armani | One night only Beijing

  metas:
    name:

london:
  title: Giorgio Armani | One night only London

  metas:
    name:

tokyo:
  title: Giorgio Armani | One night only Tokyo

  metas:
    name:
