# actions
# common settings for all actions in this controller
common:
  metas:
    name:
      keywords: One, Night, Only, Armani, Giorgio, Emporio, Fashion, Show, Rome, Roma
      description:
      robots: index, follow
    property:
      og:image: assets/img/og/ono-roma.jpg
      
# configs for each action
index:
  title: Giorgio Armani | Eccentrico

hong_kong:
  title: Giorgio Armani | Eccentrico in Hong Kong

milan:
  title: Giorgio Armani | Eccentrico in Milan

rome:
  title: Giorgio Armani | Eccentrico in Rome
        
tokyo:
  title: Giorgio Armani | Eccentrico in Tokyo
