# actions
# common settings for all actions in this controller
common:
      
# configs for each action
index:
  title: Giorgio Armani | Eccentrico

  metas:
    name:

hong_kong:
  title: Giorgio Armani | Eccentrico in Hong Kong
  
  metas:
    name:

milan:
  title: Giorgio Armani | Eccentrico in Milan
  
  metas:
    name:

rome:
  title: Giorgio Armani | Eccentrico in Rome

  metas:
    name:
        
tokyo:
  title: Giorgio Armani | Eccentrico in Tokyo

  metas:
    name:
