# actions
# common settings for all actions in this controller
common:
  title: Mark Heggie. 
  css:
    site:
      
  js:
    site:
      
# configs for each action
index:
  title: Mark Heggie - Bio

  metas:
    name:
      description: Mark Heggie's official bio.

  css:
    site:

  js:
    site:
      - news/index